# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: IGRF-13 Evaluation
author: "IAGA V MOD"
logo: ""
only_build_toc_files: true

execute:
  execute_notebooks: off

launch_buttons:
  notebook_interface        : jupyterlab
  jupyterhub_url            : "https://vre.vires.services"
  binderhub_url             : "https://mybinder.org"

repository:
  url: https://github.com/IAGA-VMOD/IGRF13eval/
  branch: main
